description: bart_quant_xsum

target:
  service: aml
  # name: tscience-a100-80g-eastus
  name: A100-80G-PCIE-westus3
  # name: V10032G
  # name: A100EastUS
  # name: openai-A10080G
  # name: A10080G
  # name: gpu-v100-32g
  # name: gpu-a100-80g


environment:
  image: pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime
  image_setup:
    - apt-get -y update
    - apt-get -y install wget
    - apt-get -y install git
  setup:
    - pip install git+https://github.com/huggingface/transformers
    - pip install git+https://github.com/huggingface/accelerate
    - pip install evaluate scikit-learn scipy typing_extensions einops
    - pip install datasets sentencepiece setuptools rouge-score nltk openai
    - pip install tensorboard tensorboardX

storage:
  output:
    storage_account_name: tsinterns
    container_name: t-qingru
    mount_dir: /mnt/t-qingru

code:
  local_dir: ../

jobs:
- name: bart_quant_xsum
  sku: 1xG8
  process_count_per_node: 1
  submit_args:
    container_args:
      cpus: 32
  command:
  - CUDA_VISIBLE_DEVICES=0 torchrun --rdzv-backend=c10d --rdzv-endpoint=localhost:10 --nnodes=1 --nproc-per-node=1 run_summarization.py --num_bits 4 --num_iter 1 --reduced_rank 8 --learning_rate 5e-5 --seed 42 --num_epochs 15 --model_name_or_path facebook/bart-large --do_train --do_eval --do_predict --dataset_name cnn_dailymail --dataset_config "3.0.0" --output_dir /mnt/t-qingru/exp_results --per_device_train_batch_size 32 --per_device_eval_batch_size 32 --overwrite_output_dir --predict_with_generate --report_to tensorboard --path_to_model_zoo /mnt/t-qingru/yixiao_model_zoo/ --logging_steps 100 --eval_steps 1000 --save_steps 2000 &
  - CUDA_VISIBLE_DEVICES=1 torchrun --rdzv-backend=c10d --rdzv-endpoint=localhost:10 --nnodes=1 --nproc-per-node=1 run_summarization.py --num_bits 4 --num_iter 1 --reduced_rank 8 --learning_rate 9e-5 --seed 42 --num_epochs 15 --model_name_or_path facebook/bart-large --do_train --do_eval --do_predict --dataset_name cnn_dailymail --dataset_config "3.0.0" --output_dir /mnt/t-qingru/exp_results --per_device_train_batch_size 32 --per_device_eval_batch_size 32 --overwrite_output_dir --predict_with_generate --report_to tensorboard --path_to_model_zoo /mnt/t-qingru/yixiao_model_zoo/ --logging_steps 100 --eval_steps 1000 --save_steps 2000 &
  - CUDA_VISIBLE_DEVICES=2 torchrun --rdzv-backend=c10d --rdzv-endpoint=localhost:10 --nnodes=1 --nproc-per-node=1 run_summarization.py --num_bits 4 --num_iter 0 --reduced_rank 8 --learning_rate 5e-5 --seed 42 --num_epochs 15 --model_name_or_path facebook/bart-large --do_train --do_eval --do_predict --dataset_name cnn_dailymail --dataset_config "3.0.0" --output_dir /mnt/t-qingru/exp_results --per_device_train_batch_size 32 --per_device_eval_batch_size 32 --overwrite_output_dir --predict_with_generate --report_to tensorboard --path_to_model_zoo /mnt/t-qingru/yixiao_model_zoo/ --logging_steps 100 --eval_steps 1000 --save_steps 2000 &
  - sleep 2400
  - CUDA_VISIBLE_DEVICES=3 torchrun --rdzv-backend=c10d --rdzv-endpoint=localhost:10 --nnodes=1 --nproc-per-node=1 run_summarization.py --num_bits 4 --num_iter 0 --reduced_rank 8 --learning_rate 9e-5 --seed 42 --num_epochs 15 --model_name_or_path facebook/bart-large --do_train --do_eval --do_predict --dataset_name cnn_dailymail --dataset_config "3.0.0" --output_dir /mnt/t-qingru/exp_results --per_device_train_batch_size 32 --per_device_eval_batch_size 32 --overwrite_output_dir --predict_with_generate --report_to tensorboard --path_to_model_zoo /mnt/t-qingru/yixiao_model_zoo/ --logging_steps 100 --eval_steps 1000 --save_steps 2000